#!/bin/bash
#This export line should be set according to the MATLAB calling file
export LD_LIBRARY_PATH=$PWD/../openMHA/bin 
#This export line should be set according to the MATLAB calling file
export PATH=$PATH:$PWD/../openMHA/bin
#The configuration path should be set according to the MATLAB calling file

mha --log=CON --port=$1 ?read:../openMHA/mha/configurations/dynamiccompression.cfg
